<!DOCTYPE html>
<html lang="en">

<head>
    <?php echo $this->getChildHtml('head'); ?>
</head>

<body>
    <div class="header">
        <?php echo $this->getChildHtml('header'); ?>
    </div> admin
    <div class="content">
        <!-- <div class="left">Left</div> -->
        <!-- <div class="content"> -->

            <?php echo $this->getChildHtml('content'); ?>
        <!-- </div> -->
        <!-- <div class="right">Right</div> -->
    </div>
    <div class="footer">
        <?php echo $this->getChildHtml('footer'); ?>
    </div>
</body>

</html>