<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Document</title>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.11.5/css/jquery.dataTables.css">


<?php $css = $this->getCss();
if (count($css)):
    foreach ($css as $_css): ?>
        <link rel="stylesheet" href="<?php echo Mage::getBaseUrl().$_css; ?>">
    <?php endforeach;
endif; ?>




<?php $jsScript = $this->getJs(); ?>
<?php if (count($jsScript)) : ?>
    <?php foreach ($jsScript as $_js) : ?>
        <script src="<?php echo Mage::getBaseUrl().$_js; ?>"></script>
    <?php endforeach; ?>
<?php endif; ?>